---

- name: Install
  yum:
    name: "kibana-{{ kibana_version }}-1.{{ ansible_architecture }}"
    state: present

- name: Create directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
  loop:
  - "{{ kibana_log_dir }}"
  - "{{ kibana_pid_dir }}"
  - "{{ kibana_data_dir }}"

- name: include kibana-ssl.yml
  include: kibana-ssl.yml
  when: kibana_enable_ssl
  tags:
  - ssl

- name: include kibana-es-ssl.yml
  include: kibana-ssl.yml
  when: kibana_enable_elasticsearch_ssl
  tags:
  - ssl

- name: Configure
  template:
    src: kibana.yml.j2
    dest: "{{ kibana_conf_dir }}/kibana.yml"
  notify: restart kibana

- name: enable Kibana
  systemd:
    name: kibana
    enabled: yes

